### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by pavarinmicaela** [pdep-utn-frd/presentacion-Fabiana79#3]
Hola Fabiana! 
Creo, no estoy segura, que no creaste el archivo readme.md como decía la consigna. También podías usar Markdown para darle formato a la presentación.

Saludos! Micaela.

**Comment by FabiPadilla** [comment]
Hola pavarinmicaela !.Tenés razón,pensé que lo había creado luego de aceptar la tarea.Gracias. Saludos!
